<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>

    <xacro:property name="length" value="0.5"/>
    <xacro:property name="width" value="0.5"/>
    <xacro:property name="height" value="0.5"/>

    <material name="blue">
        <color rgba="0 0 0.8 0.5"/>
    </material>

    <xacro:macro name="assembled_robot" params="
        parent
        *origin
        ur_type
        joint_limits_parameters_file
        kinematics_parameters_file
        physical_parameters_file
        visual_parameters_file
        ">

        <!--  this joint fixes the table to the world link given as a parameter -->
        <joint name="table_base_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="table"/>
            <origin xyz="0 0 ${height}" rpy="0 0 0"/>
        </joint>

        <link name="table">
            <visual>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 -${height/2}"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 -${height/2}"/>
            </collision>
        </link>

        <link name="robot_mount"/>

        <joint name="base_to_robot_mount" type="fixed">
            <parent link="table"/>
            <child link="robot_mount"/>
            <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        </joint>

        <!-- This will create the specific robot -->
        <xacro:ur_robot
            name="${ur_type}"
            tf_prefix="${ur_type}_"
            parent="robot_mount"
            joint_limits_parameters_file="${joint_limits_parameters_file}"
            kinematics_parameters_file="${kinematics_parameters_file}"
            physical_parameters_file="${physical_parameters_file}"
            visual_parameters_file="${visual_parameters_file}"
        >
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:ur_robot>
    </xacro:macro>

</robot>